# Generated by Django 3.2.16 on 2022-12-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrating',
            name='rating',
            field=models.SmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='оценка'),
        ),
        migrations.AlterUniqueTogether(
            name='bookrating',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='bookrating',
            constraint=models.UniqueConstraint(fields=('book', 'user'), name='book_user_unique'),
        ),
    ]
