# Generated by Django 3.2.16 on 2022-12-11 16:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'теги',
                'default_related_name': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_data', models.DateField(auto_created=True, verbose_name='дата создания')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('content', models.FileField(upload_to='books/%Y/%m', validators=[django.core.validators.FileExtensionValidator(['pdf', 'fb2'])], verbose_name='содержимое')),
                ('preview', models.ImageField(upload_to='previews/%Y/%m', verbose_name='превью')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликовано')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='заблокировано')),
                ('description', models.TextField(default='Без описания', max_length=3000, verbose_name='описание')),
                ('slug', models.SlugField(max_length=100, verbose_name='slug')),
                ('age_rating', models.TextField(blank=True, choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('16+', '16+'), ('18+', '18+')], null=True, verbose_name='возрастной рейтинг')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(related_name='books', to='catalog.Tag')),
            ],
            options={
                'verbose_name': 'книга',
                'verbose_name_plural': 'книги',
                'default_related_name': 'books',
            },
        ),
    ]
