# Generated by Django 3.2.16 on 2022-12-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='creation_data',
            field=models.DateField(auto_created=True, auto_now_add=True, verbose_name='дата создания'),
        ),
    ]
