# Generated by Django 3.2.16 on 2022-12-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bookchapter',
            name='chapter_number_unique',
        ),
        migrations.AddConstraint(
            model_name='bookchapter',
            constraint=models.UniqueConstraint(fields=('book',), name='chapter_number_unique'),
        ),
    ]
