# Generated by Django 3.2.16 on 2022-12-24 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.SmallIntegerField(choices=[(0, 'Другое'), (1, 'Пропаганда запрещенных веществ'), (2, 'Пропаганда ЛГБТ'), (3, 'Несоответсвие возрастному рейтингу'), (4, 'Разжигание вражды и ненависти'), (5, 'Нарушение авторского права'), (6, 'Нарушение правил сайта')], default=0, verbose_name='причина')),
                ('content', models.CharField(max_length=5000, verbose_name='объяснение')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, verbose_name='дата и время создания')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.book', verbose_name='книга')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='отправитель')),
            ],
            options={
                'verbose_name': 'Жалоба',
                'verbose_name_plural': 'Жалобы',
            },
        ),
    ]
