# Generated by Django 3.2.16 on 2022-12-23 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'default_related_name': 'quotes', 'ordering': ('-creation_date',)},
        ),
    ]
